### PR TITLE
Added GitPod

### LINKED ISSUE #8: [FEAT] Gitpodify Project
add a best practice about integrating gitpod in open source projects

### PR DESCRIPTION
**Pull request by avneesh0612**
## 🛠️ Fixes Issue
closes #8 

## 👨‍💻 Changes proposed
I have added GitPod in the project Readme

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by suitupstan — CHANGES_REQUESTED** [review]
Didn't the docs mention to add a `.gitpod.yml` file?

**Comment by avneesh0612** [comment]
It did, but do we need any initializing code here?

**Comment by suitupstan** [comment]
> It did, but do we need any initializing code here?

nope, but at least add the config to add comments to PRs and more...

**Comment by avneesh0612** [comment]
Okay

**Comment by avneesh0612** [comment]
Added it :)

**Comment by avneesh0612** [comment]
Wait, it didn't push 🤔

**Comment by avneesh0612** [comment]
hmm, was on the wrong branch :P

**Review by suitupstan — APPROVED** [review]

**Pull request merged**
